services:
  mysql:
    image: mysql:8.0
    container_name: vlbc-db
    environment:
      MYSQL_ROOT_PASSWORD: vinicius
      MYSQL_DATABASE: vlbc-db
      MYSQL_USER: vinicius
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
