server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/vlbc-db?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: vinicius
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none